services:

  postgres:
    image: postgres:14.22-bookworm
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  postgresql_data:
  
